### ISSUE TITLE
lag_warning mod

### ISSUE THREAD

**Issue by BuckarooBanzay** [Montandalar/forks-modpack#1]
(sorry, i'm too lazy to log into the forums)

But yeah: feel free to do whatever you want with the `lag_warning` mod, i wrote that under an alias at that time,
not sure if i even included a license :yum: its a small mod anyway...

**Comment by Montandalar** [comment]
Great, and I hope it's the same for mesecons_ratelimiter?

**Comment by BuckarooBanzay** [comment]
> Great, and I hope it's the same for mesecons_ratelimiter?

Ah, that one lives here now: https://github.com/minetest-monitoring/mesecons_ratelimiter but it did not help much with the mesecons-lag issues, it just deduplicates some events

**Comment by Montandalar** [comment]
Great, thanks
