### ISSUE TITLE
Mods folders are empty

### ISSUE THREAD

**Issue by W3RQ01** [Montandalar/forks-modpack#2]
I downloaded the repository and when i opened the folder of the technic mod i find it completely empty, same  for the other folders except for the advtrains folder

**Comment by Montandalar** [comment]
Were you able to resolve this issue by running one of the scripts included that downloads the mods?

**Comment by Montandalar** [comment]
Submodules are working fine, git submodule is required. I will consider releases in future, but the best way to get the forks modpack is probably still the official mod archive.
